services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/crowdfunded
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - crowdfunded-network

  db:
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crowdfunded
    volumes:
      - postgres-data-new:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - crowdfunded-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  postgres-data-new:

networks:
  crowdfunded-network:
    driver: bridge