services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/crowdfunded
      - DENO_DIR=/app/.deno
    volumes:
      - deno-cache:/app/.deno
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - crowdfunded-network

  db:
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crowdfunded
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - crowdfunded-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  deno-cache:

networks:
  crowdfunded-network:
    driver: bridge